<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale [
<!ELEMENT locale (exception)>
<!ELEMENT exception (ANY)+>
<!ELEMENT warning (message)+>
<!ELEMENT error (message)+>
<!ELEMENT fatalerror (message)+>
<!ELEMENT message (#PCDATA)>
<!ATTLIST locale name CDATA #REQUIRED>
<!ATTLIST message name CDATA #REQUIRED>
]>
<locale name="francais">
  <exception>
    <blob>
      <error>
        <message name="UnableToOpenBlob">
          impossible d'ouvrir l'image
        </message>
        <message name="UnableToOpenFile">
          impossible d'ouvrir le fichier
        </message>
        <message name="UnableToReadBlob">
          impossible de lire un blob
        </message>
        <message name="UnableToWriteBlob">
          impossible d'écrire un blob
        </message>
        <message name="UnrecognizedImageFormat">
          format d'image non reconnu
        </message>
        <message name="ZeroLengthBlobNotPermitted">
          blob de taille nulle non autorisé
        </message>
      </error>
    </blob>
    <cache>
      <error>
        <message name="CacheResourcesExhausted">
          Ressources du cache épuisées
        </message>
        <message name="IncompatibleAPI">
          incompatible API
        </message>
        <message name="NoPixelsDefinedInCache">
          pas de pixels définis dans le cache
        </message>
        <message name="PixelCacheIsNotOpen">
          cache pixels non ouvert
        </message>
        <message name="PixelsAreNotAuthentic">
          pixels are not authentic
        </message>
        <message name="UnableToCloneCache">
          impossible de clôner le cache
        </message>
        <message name="UnableToExtendCache">
          impossible d'étendre le cache
        </message>
        <message name="UnableToGetCacheNexus">
          impossible de récupérer le nexus du cache
        </message>
        <message name="UnableToOpenPixelCache">
          impossible d'ouvrir le cache pixels
        </message>
        <message name="UnableToPersistPixelCache">
          impossible de rendre persistant le cache pixels
        </message>
        <message name="UnableToReadPixelCache">
          impossible de lire le cache pixels
        </message>
        <message name="UnableToWritePixelCache">
          impossible d'écrire le cache pixels
        </message>
      </error>
      <fatalerror>
        <message name="UnableToAcquireCacheView">
          échec allocation cache view
        </message>
        <message name="UnableToExtendPixelCache">
          impossible extend le cache pixels
        </message>
      </fatalerror>
    </cache>
    <coder>
      <error>
        <message name="ColormapTypeNotSupported">
          table de couleurs non supportée
        </message>
        <message name="ColorspaceModelIsNotSupported">
          espace colorimétrique non supporté
        </message>
        <message name="DataEncodingSchemeIsNotSupported">
          schéma d'encodage de données non supporté
        </message>
        <message name="DataStorageTypeIsNotSupported">
          type de stockage de données non supporté
        </message>
        <message name="DeltaPNGNotSupported">
          delta-PNG non supporté
        </message>
        <message name="EncryptedWPGImageFileNotSupported">
          image WPG encryptée non supportée
        </message>
        <message name="FractalCompressNotSupported">
          compression Fractal non supportée
        </message>
        <message name="ImageColumnOrRowSizeIsNotSupported">
          nombre de lignes ou de colonnes dans l'image non supporté
        </message>
        <message name="ImageDoesNotHaveAClipMask">
          image sans masque de coupe
        </message>
        <message name="ImageDoesNotHaveAThumbnail">
          image sans vignette EXIF
        </message>
        <message name="ImageDoesNotHaveAnAlphaChannel">
          l'image n'a pas de canal de transparence
        </message>
        <message name="ImageDoesNotHaveAMaskChannel">
          image sans masque de canal
        </message>
        <message name="ImageIsNotTiled">
          l'image n'a pas tiled
        </message>
        <message name="IrregularChannelGeometryNotSupported">
          irregular channel geometry not supported
        </message>
        <message name="JNGCompressNotSupported">
          compression JNG non supportée
        </message>
        <message name="JPEGCompressNotSupported">
          compression JPEG non supportée
        </message>
        <message name="JPEGEmbeddingFailed">
          Échec incorporation JPEG
        </message>
        <message name="LocationTypeIsNotSupported">
          Type d'emplacement non supporté
        </message>
        <message name="MapStorageTypeIsNotSupported">
          Map storage type is not supported
        </message>
        <message name="MultidimensionalMatricesAreNotSupported">
          Matrices multi-dimensionnelles non supportées
        </message>
        <message name="MultipleRecordListNotSupported">
          Liste à enregistrements multiples non supportée
        </message>
        <message name="NoBitmapOnClipboard">
          pas de bitmap dans le presse-papier
        </message>
        <message name="NoAPP1DataIsAvailable">
          pas de données APP1 disponibles
        </message>
        <message name="No8BIMDataIsAvailable">
          pas de données 8BIM disponibles
        </message>
        <message name="NoColorProfileIsAvailable">
          pas de profil colorimétrique disponible
        </message>
        <message name="NoDataReturned">
          aucune donnée fournie
        </message>
        <message name="NoImagesDefined">
          aucune image définie
        </message>
        <message name="NoImageVectorGraphics">
          pas d'image en graphique vectoriel; unable to generate SVG
        </message>
        <message name="NoIPTCProfileAvailable">
          pas de profil IPTC disponible
        </message>
        <message name="NumberOfImagesIsNotSupported">
          nombre d'images non supporté
        </message>
        <message name="OnlyContinuousTonePictureSupported">
          seules les images à tons continus sont supportées
        </message>
        <message name="OnlyLevelZerofilesSupported">
          seuls les fichiers de niveau zéro sont supportés
        </message>
        <message name="PNGCompressNotSupported">
          compression PNG non supportée
        </message>
        <message name="RLECompressNotSupported">
          compression RLE non supportée
        </message>
        <message name="UnableToCopyProfile">
          impossible de copier le profil
        </message>
        <message name="UnableToCreateBitmap">
          impossible de créer la bitmap
        </message>
        <message name="UnableToCreateADC">
          impossible de créer un DC
        </message>
        <message name="UnableToDecompressImage">
          impossible de décompresser l'image
        </message>
        <message name="UnableToWriteMPEGParameters">
          impossible d'écrire les paramètres MPEG
        </message>
        <message name="UnableToZipCompressImage">
          impossible de compresser l'image en zip
        </message>
        <message name="UnsupportedRLEImagefile">
          Fichier image RLE non supporté
        </message>
        <message name="ZIPCompressNotSupported">
          compression ZIP non supportée
        </message>
      </error>
      <warning>
        <message name="LosslessToLossyJPEGConversion">
          Conversion JPEG sans perte vers JPEG avec perte
        </message>
      </warning>
    </coder>
    <configure>
      <error>
        <message name="IncludeElementNestedTooDeeply">
          trop de niveau d'inclusion d'éléments
        </message>
        <message name="PolicyValidationException">
          security policy failed to validate
        </message>
      </error>
      <warning>
        <message name="UnableToOpenConfigureFile">
          impossible d'accéder au fichier de configuration
        </message>
        <message name="UnableToOpenModuleFile">
          impossible d'ouvrir le fichier de module
        </message>
      </warning>
    </configure>
    <corrupt>
      <image>
        <error>
          <message name="AnErrorHasOccurredReadingFromFile">
            Une erreur est survenue lors de la lecture du fichier
          </message>
          <message name="AnErrorHasOccurredWritingToFile">
            Une erreur est survenue lors de l'écriture dans un fichier
          </message>
          <message name="CipherSupportNotEnabled">
            cipher support not enabled
          </message>
          <message name="ColormapExceeds256Colors">
            Table de couleurs a plus que 256 couleurs
          </message>
          <message name="CorruptImage">
            Image corrompue
          </message>
          <message name="FileFormatVersionMismatch">
            erreur sur la version du format de fichier
          </message>
          <message name="ImageDepthNotSupported">
            profondeur d'image non supportée
          </message>
          <message name="ImageFileDoesNotContainAnyImageData">
            le fichier image ne contient pas de données d'image
          </message>
          <message name="ImageTypeNotSupported">
            type d'image non supporté
          </message>
          <message name="ImproperImageHeader">
            En-tête d'image incorrect
          </message>
          <message name="InsufficientImageDataInFile">
            Pas assez de données d'image dans le fichier
          </message>
          <message name="InvalidColormapIndex">
            Index dans la table de couleurs invalide
          </message>
          <message name="InvalidPixel">
            Pixel invalide
          </message>
          <message name="LengthAndFilesizeDoNotMatch">
            Longueur et taille du fichier ne correspondent pas
          </message>
          <message name="MaximumChannelsExceeded">
            maximum de canals dépassent les
          </message>
          <message name="MissingImageChannel">
            absence l'image canel
          </message>
          <message name="NegativeOrZeroImageSize">
            Taille d'image négative ou nulle
          </message>
          <message name="NonOS2HeaderSizeError">
            Taille en-tête BMP non-OS2 plus petite que 40
          </message>
          <message name="NotEnoughPixelData">
            Pas assez de données pixel
          </message>
          <message name="NotEnoughTiles">
            Pas assez de tuiles trouvées à ce niveau
          </message>
          <message name="TooMuchImageDataInFile">
            Trop de données d'image dans le fichier
          </message>
          <message name="StaticPlanesValueNotEqualToOne">
            Valeur statique des plans différente de 1
          </message>
          <message name="UnableToReadExtensionBlock">
            impossible de lire le bloc d'extension
          </message>
          <message name="UnableToReadImageHeader">
            impossible de lire l'en-tête de l'image
          </message>
          <message name="UnableToReadImageData">
            impossible de lire les données de l'image
          </message>
          <message name="UnableToRunlengthDecodeImage">
            impossible de décoder l'image avec « runlength »
          </message>
          <message name="UnableToUncompressImage">
            impossible de décompresser l'image
          </message>
          <message name="UnexpectedEndOfFile">
            fin de fichier inattendue
          </message>
          <message name="UnexpectedSamplingFactor">
            facteur d'échantillonnage inattendu
          </message>
          <message name="UnknownPatternType">
            type de motif inconnu
          </message>
          <message name="UnrecognizedAlphaChannelOption">
            alpha de canal l'option non reconnus
          </message>
          <message name="UnrecognizedImageCompression">
            compression non reconnue
          </message>
          <message name="UnrecognizedNumberOfColors">
            nombre de couleurs non reconnu
          </message>
          <message name="UnsupportedBitsPerPixel">
            bits par pixel non supporté
          </message>
        </error>
        <fatalerror>
          <message name="UnableToPersistKey">
            impossible de rendre la clé persistante
          </message>
        </fatalerror>
        <warning>
          <message name="InsufficientImageDataInFile">
            pas assez de données d'image dans le fichier
          </message>
          <message name="LengthAndFilesizeDoNotMatch">
            Longueur et taille du fichier ne correspondent pas
          </message>
          <message name="SkipToSyncByte">
            Image PCD corrompue, saut à l'octet de synchronisation
          </message>
        </warning>
      </image>
    </corrupt>
    <delegate>
      <error>
        <message name="DelegateFailed">
          Échec de la délégation
        </message>
        <message name="FailedToComputeOutputSize">
          Impossible de calculer la taille en sortie
        </message>
        <message name="FailedToRenderFile">
          Impossible de générer le fichier
        </message>
        <message name="FailedToScanFile">
          Impossible de lire le fichier
        </message>
        <message name="NoTagFound">
          pas de balise trouvée
        </message>
        <message name="PCLDelegateFailed">
          Échec délégation PCL
        </message>
        <message name="PostscriptDelegateFailed">
          Échec délégation Postscript
        </message>
        <message name="UnableToCreateImage">
          impossible de créer l'image
        </message>
        <message name="UnableToDecodeImageFile">
          impossible de décoder le fichier d'image
        </message>
        <message name="UnableToEncodeImageFile">
          impossible d'encoder le fichier d'image
        </message>
        <message name="UnableToInitializeFPXLibrary">
          impossible d'initialiser la librairie FPX
        </message>
        <message name="UnableToInitializeWMFLibrary">
          impossible d'initialiser la librairie WMF
        </message>
        <message name="UnableToManageJP2Stream">
          impossible de gérer un flux JP2
        </message>
        <message name="UnableToReadAspectRatio">
          impossible de lire le ratio d'aspect
        </message>
        <message name="UnableToReadSummaryInfo">
          impossible de lire le résumé des informations
        </message>
        <message name="UnableToSetAffineMatrix">
          impossible de fixer la matrice affine
        </message>
        <message name="UnableToSetAspectRatio">
          impossible de fixer le ratio d'aspect
        </message>
        <message name="UnableToSetColorTwist">
          impossible de fixer la torsion de couleur
        </message>
        <message name="UnableToSetContrast">
          impossible de fixer le contraste
        </message>
        <message name="UnableToSetFilteringValue">
          impossible de fixer la valeur du filtre
        </message>
        <message name="UnableToSetImageTitle">
          impossible de fixer le titre de l'image
        </message>
        <message name="UnableToSetJPEGLevel">
          impossible de fixer le niveau JPEG
        </message>
        <message name="UnableToSetRegionOfInterest">
          impossible de fixer la zone d'intérêt
        </message>
        <message name="UnableToSetSummaryInfo">
          impossible de fixer le résumé des informations
        </message>
        <message name="UnableToWriteSVGFormat">
          impossible d'écrire au format SVG
        </message>
        <message name="XPSDelegateFailed">
          Échec délégation XPS
        </message>
      </error>
    </delegate>
    <draw>
      <error>
        <message name="AlreadyPushingPatternDefinition">
          Définition de motif déjà fixée
        </message>
        <message name="NonconformingDrawingPrimitiveDefinition">
          Définition de primitive de dessin non conforme
        </message>
        <message name="NotARelativeURL">
          URL non relative
        </message>
        <message name="NotCurrentlyPushingPatternDefinition">
          Actuellement pas de définition de motif
        </message>
        <message name="SegmentStackOverflow">
          Débordement pile de segments
        </message>
        <message name="TooManyBezierCoordinates">
          Trop de coordonnées bézier
        </message>
        <message name="UnableToPrint">
          impossible d'imprimer
        </message>
        <message name="UnbalancedGraphicContextPushPop">
          erreur d'imbrication des contextes graphiques
        </message>
        <message name="URLNotFound">
          URL inaccessible
        </message>
        <message name="VectorGraphicsNestedTooDeeply">
          trop d'imbrication de vector graphiques
        </message>
      </error>
    </draw>
    <file>
      <open>
        <error>
          <message name="AnErrorHasOccurredReadingFromFile">
            an error has occurred reading from file
          </message>
          <message name="UnableToCreateTemporaryFile">
            impossible de créer un fichier temporaire
          </message>
          <message name="UnableToOpenFile">
            impossible d'ouvrir le fichier
          </message>
          <message name="UnableToWriteFile">
            impossible d'enregistrer le fichier
          </message>
        </error>
      </open>
    </file>
    <filter>
      <error>
        <message name="FilterFailed">
          filter failed
        </message>
      </error>
    </filter>
    <image>
      <error>
        <message name="AngleIsDiscontinuous">
          angle discontinu
        </message>
        <message name="ColormappedImageRequired">
          Image avec table de couleurs requise
        </message>
        <message name="ColorSeparatedImageRequired">
          Image avec couleurs séparées requise
        </message>
        <message name="ColorspaceColorProfileMismatch">
          Le profil colorimétrique ne peut fonctionner que dans un autre espace colorimétrique
        </message>
        <message name="ExplicitCoderNotAllowed">
          explicit coder not allowed
        </message>
        <message name="ImageColorspaceDiffers">
          différences dans les espaces colorimétriques de l'image
        </message>
        <message name="ImageDepthNotSupported">
          profondeur d'image non supportée
        </message>
        <message name="ImageMorphologyDiffers">
          différences dans la morphology de l'image
        </message>
        <message name="ImageListRequired">
          une liste d'images est requise
        </message>
        <message name="ImageSequenceRequired">
          une séquence d'images est requise
        </message>
        <message name="ImageSizeDiffers">
          différences dans la taille de l'image
        </message>
        <message name="LeftAndRightImageSizesDiffer">
          différences dans les tailles des images gauche et droite
        </message>
        <message name="ImageSizeLimitExceeded">
          Image dimension exceeds maximum supported size
        </message>
        <message name="NegativeOrZeroImageSize">
          Taille d'image négative ou nulle
        </message>
        <message name="NoImagesWereFound">
          aucune image trouvée
        </message>
        <message name="NoImagesWereLoaded">
          aucune image chargée
        </message>
        <message name="TooManyClusters">
          trop de grappes
        </message>
        <message name="UnableToCreateColorTransform">
          impossible de créer la transformation de couleurs
        </message>
        <message name="WidthOrHeightExceedsLimit">
          Largeur ou hauteur dépassent les limites
        </message>
      </error>
      <warning>
        <message name="AssociateProfile">
          associate profile with image, a source and destination color profile required for transform
        </message>
        <message name="ImagesTooDissimilar">
          images too dissimilar
        </message>
        <message name="UnableToTransformColorspace">
          impossible de colorimétrique la transformation
        </message>
      </warning>
    </image>
    <missing>
      <delegate>
        <error>
          <message name="DelegateLibrarySupportNotBuiltIn">
            delegate library support not built-in
          </message>
          <message name="NoDecodeDelegateForThisImageFormat">
            pas de délégué pour décoder ce format d'image
          </message>
          <message name="NoEncodeDelegateForThisImageFormat">
            pas de délégué pour encoder ce format d'image
          </message>
        </error>
        <warning>
          <message name="DelegateLibrarySupportNotBuiltIn">
            delegate library support not built-in
          </message>
          <message name="NoEncodeDelegateForThisImageFormat">
            pas de délégué pour encoder ce format d'image
          </message>
        </warning>
      </delegate>
    </missing>
    <module>
      <error>
        <message name="ImageCoderSignatureMismatch">
          image coder signature mismatch
        </message>
        <message name="ImageFilterSignatureMismatch">
          image filter signature mismatch
        </message>
        <message name="UnableToLoadModule">
          impossible de charger le module
        </message>
        <message name="UnableToRegisterImageFormat">
          impossible d'enregister le format d'image
        </message>
      </error>
      <fatalerror>
        <message name="UnableToInitializeModuleLoader">
          impossible d'initialiser le chargeur de module
        </message>
      </fatalerror>
      <warning>
        <message name="UnableToCloseModule">
          impossible de fermer le module
        </message>
      </warning>
    </module>
    <option>
      <error>
        <message name="ClutImageRequired">
          color lookup table image requise
        </message>
        <message name="CompositeImageRequired">
          image composite requise
        </message>
        <message name="CurlyBracesNestedTooDeeply">
          trop d'imbrication de curly braces
        </message>
        <message name="DepreciatedOptionNoCode">
          l'option dépréciée, incapable d'exécuter
        </message>
        <message name="DivideByZero">
          division par zéro
        </message>
        <message name="FrameIsLessThanImageSize">
          trame inférieure à la taille de l'image
        </message>
        <message name="GeometryDimensionsAreZero">
          dimensions de la géométrie nulles
        </message>
        <message name="GeometryDoesNotContainImage">
          image non incluse dans la géométrie
        </message>
        <message name="ImageSequenceRequired">
          une séquence d'images est requise
        </message>
        <message name="InterpretPropertyFailure">
          l'échec d'interpréter s'échappe de propriété d'image
        </message>
        <message name="InvalidArgument">
          argument invalide pour l'option
        </message>
        <message name="InvalidUseOfOption">
          Invalide utilisation de l'option
        </message>
        <message name="InvalidGeometry">
          géométrie invalide
        </message>
        <message name="InvalidImageIndex">
          index de l'image non valide
        </message>
        <message name="InvalidNumberList">
          liste des numéros non valide
        </message>
        <message name="InvalidSetting">
          invalide de réglage
        </message>
        <message name="ImagesAreNotTheSameSize">
          images diffèrent par la taille
        </message>
        <message name="ImagePagesAreNotCoalesced">
          image pages are not coalesced
        </message>
        <message name="ImageSizeMustExceedBevelWidth">
          la taille doit être supérieure à la largeur de la facette
        </message>
        <message name="ImageWidthsOrHeightsDiffer">
          différences dans la hauteur ou la largeur de l'image
        </message>
        <message name="KernelWidthMustBeAnOddNumber">
          la largeur du grain doit être un nombre impair
        </message>
        <message name="LabelExpected">
          label expected
        </message>
        <message name="MapImageRequired">
          image map requise
        </message>
        <message name="MissingArgument">
          manque argument obligatoire
        </message>
        <message name="MissingAnImageFilename">
          nom de fichier d'image absent
        </message>
        <message name="MissingExpression">
          expression absente
        </message>
        <message name="MissingNullSeparator">
          Séparateur nul pour liste d'image absent
        </message>
        <message name="MissingOutputFilename">
          output filename absente
        </message>
        <message name="MustSpecifyAnImageName">
          Il faut spécifier un nom d'image
        </message>
        <message name="MustSpecifyImageDepth">
          Il faut spécifier la profondeur d'image
        </message>
        <message name="MustSpecifyImageSize">
          Il faut spécifier une taille d'image
        </message>
        <message name="NoBlobDefined">
          pas de définition de blob « Binary Large OBjects »
        </message>
        <message name="NoClipPathDefined">
          pas de chemin de coupe défini
        </message>
        <message name="NoImagesForWrite">
          pas d'images pour écriture
        </message>
        <message name="NoImagesFound">
          pas d'image pour un fonctionnement
        </message>
        <message name="NoImageVectorGraphics">
          pas de graphiques vectoriels
        </message>
        <message name="NoSuchImage">
          image inconnue
        </message>
        <message name="NoSuchImageChannel">
          image channel inconnue
        </message>
        <message name="NoSuchOption">
          option inconnue
        </message>
        <message name="NonZeroWidthAndHeightRequired">
          hauteur et largeur non nulles requises
        </message>
        <message name="NotEnoughParameters">
          not enough parameters
        </message>
        <message name="ParenthesisNestedTooDeeply">
          trop d'imbrication de parenthèses
        </message>
        <message name="ReferenceImageRequired">
          image de référence requise
        </message>
        <message name="ReferenceIsNotMyType">
          référence de type erroné
        </message>
        <message name="SteganoImageRequired">
          image stégano requise
        </message>
        <message name="StereoImageRequired">
          image stéréo requise
        </message>
        <message name="SubimageSpecificationReturnsNoImages">
          la spécification de sous-image ne permet pas de fournir des images
        </message>
        <message name="TwoOrMoreImagesRequired">
          deux ou plusieurs images nécessaires
        </message>
        <message name="UnableToAccessPath">
          incapables d'accéder chemin du fichier
        </message>
        <message name="UnableToOpenFile">
          impossible d'ouvrir le fichier
        </message>
        <message name="UnableToParseExpression">
          impossible d'analyser l'expression
        </message>
        <message name="UnableToParseKernel">
          impossible d'analyser l'kernel string
        </message>
        <message name="UnbalancedBraces">
          brace non fermée
        </message>
        <message name="UnbalancedParenthesis">
          parenthèse non fermée
        </message>
        <message name="UndefinedVariable">
          undefined variable
        </message>
        <message name="UnrecognizedAttribute">
          attribut non reconnu
        </message>
        <message name="UnrecognizedChannelType">
          type de canal non reconnu
        </message>
        <message name="UnrecognizedColor">
          couleur non reconnue
        </message>
        <message name="UnrecognizedColorspace">
          espace colorimétrique non reconnu
        </message>
        <message name="UnrecognizedComposeOperator">
          opérateur de composition non reconnu
        </message>
        <message name="UnrecognizedCompressType">
          type de compression non reconnu
        </message>
        <message name="UnrecognizedDisposeMethod">
          méthode de disposition non reconnue
        </message>
        <message name="UnrecognizedDistortMethod">
          méthode de distortion non reconnu
        </message>
        <message name="UnrecognizedDitherMethod">
          méthode de dither non reconnue
        </message>
        <message name="UnrecognizedEndianType">
          type de boutisme non reconnu
        </message>
        <message name="UnrecognizedElement">
          élément non reconnu
        </message>
        <message name="UnrecognizedFunction">
          function non reconnu
        </message>
        <message name="UnrecognizedEvaluateOperator">
          evaluate operator non reconnu
        </message>
        <message name="UnrecognizedEventType">
          type d'événement non reconnu
        </message>
        <message name="UnrecognizedGravityType">
          type de gravité non reconnu
        </message>
        <message name="UnrecognizedImageCompression">
          compression d'image non reconnue
        </message>
        <message name="UnrecognizedImageFilter">
          filtre d'image non reconnu
        </message>
        <message name="UnrecognizedImageFormat">
          format d'image non reconnu
        </message>